//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmyAccountSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Invoice_Info
    {
        public string ItemName { get; set; }
        public double ItemCount { get; set; }
        public double ItemPrice { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public string CashierName { get; set; }
        public string BranchName { get; set; }
        public string CityName { get; set; }
        public double TotalPrice { get; set; }
        public long ID { get; set; }
    }
}
